ethereum:
  chain_id: 1

contracts:
    - name: "Mock WBTC Test Vault"
      address: "0xf2b85c389a771035a9bd147d4bf87987a7f9cf98"
      start_block: 22577826
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Mock WBTC Test Vault2"
      address: "0x0b3b3a2c11d6676816fe214b7f23446d12d762ff"
      start_block: 22634425
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "WBTC Test1"
      address: "0x3ea82bda12e3cba18e4a9fd0cf7de2fb78ca4d32"
      start_block: 22694852
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "LBTC Test1"
      address: "0x1c2d8f447167fa7d28b2ec869df9d320aa2e6a71"
      start_block: 22783642
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "LBTC Test2"
      address: "0x9fe5b9c7ddbd26d0dc93634e15eb1a5d34c85493"
      start_block: 22837541
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "USDC Test1"
      address: "0x58e3e5eeae41c4ab8f954189dc9daef8ac7a17f9"
      start_block: 22837730
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "USDC Test2"
      address: "0x94c893c7ffe53a176f42d24d2e9e0b67bc7d4360"
      start_block: 22945822
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 1"
      address: "0x401e9cb8b76b80ac582b573d5fac214fd93cfe9c"
      start_block: 23088149
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 2"
      address: "0x2d3a756906a548ee9f5130401fd6eeb39d3121d6"
      start_block: 23082177
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 3"
      address: "0xae247e07e5abfc3d5c751f1e9eb78e8cbef7f286"
      start_block: 23081984
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 4"
      address: "0x950c91dac89bf77f875d53edfd38962375c1762e"
      start_block: 23088959
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 5"
      address: "0x092404da30b0a7a5c1159969be639b63c7fb8701"
      start_block: 23117096
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 6"
      address: "0x57089f120d45e41c258a73543084990fd9555301"
      start_block: 23117347
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 7"
      address: "0x028c998126fdb787dd9ee3ce9bd00cc2701136bb"
      start_block: 23140097
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 8"
      address: "0x20cd4a9d92ca5e9e8816537db4ddd0bfdf82a924"
      start_block: 23174828
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 9"
      address: "0x78ced4c73c9ddb23661eafb403f94d30b5265970"
      start_block: 23175112
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    - name: "Neutron Vault 10"
      address: "0x8e78915edc31b994b73ab388509901b2aad90744"
      start_block: 23175207
      abi_path: "vault.abi.json"
      events:
        - "Deposit"
        - "Transfer"
        - "WithdrawRequested"
        - "RateUpdated"
    
    
    
